--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-02-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "GOODS"."COMPANY" 
   (	"COMPANYCODE" VARCHAR2(20 BYTE), 
	"COMPANYNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GOODS.COMPANY
SET DEFINE OFF;
Insert into GOODS.COMPANY (COMPANYCODE,COMPANYNAME) values ('ABC','휴먼전자');
Insert into GOODS.COMPANY (COMPANYCODE,COMPANYNAME) values ('DEF','아트전자');
Insert into GOODS.COMPANY (COMPANYCODE,COMPANYNAME) values ('GHI','아카전자');
Insert into GOODS.COMPANY (COMPANYCODE,COMPANYNAME) values ('JKL','데미전자');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOODS"."TABLE1_PK" ON "GOODS"."COMPANY" ("COMPANYCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "GOODS"."COMPANY" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("COMPANYCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GOODS"."COMPANY" MODIFY ("COMPANYCODE" NOT NULL ENABLE);
